# Site settings
title: DEB.SURY.ORG
email: ondrej@sury.org
tag_text: Debian and Ubuntu packaging
description: Debian and Ubuntu packaging
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: oerdnj
github_username:  oerdnj

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]

